<?php

use Illuminate\Database\Seeder;
use App\CountryCurrencySymbol;

class CountryCurrencySymbolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        CountryCurrencySymbol::truncate();

        $country = array(
			  array("country"=>"Afghanistan","currency"=>"Afghanistani Afghani","code"=>"AFN","symbol"=>"؋"),
			  array("country"=>"Albania","currency"=>"Albanian Lek","code"=>"ALL","symbol"=>"Lek"),
			  array("country"=>"Algeria","currency"=>"Algerian Dinar","code"=>"DZD","symbol"=>"دج"),
			  array("country"=>"Andorra","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Angola","currency"=>"Angolan Kwanza","code"=>"AOA","symbol"=>"Kz"),
			  array("country"=>"Antigua and Barbuda","currency"=>"East Caribbean Dollar","code"=>"XCD","symbol"=>"$"),
			  array("country"=>"Argentina","currency"=>"Argentine Peso","code"=>"ARS","symbol"=>"$"),
			  array("country"=>"Armenia","currency"=>"Armenian Dram","code"=>"AMD","symbol"=>"դր"),
			  array("country"=>"Armenia","currency"=>"Armenian Dram","code"=>"AMD","symbol"=>"դր."),
			  array("country"=>"Australia","currency"=>"Australian Dollar","code"=>"AUD","symbol"=>"$"),
			  array("country"=>"Austria","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Azerbaijan","currency"=>"Azerbaijani Manat","code"=>"AZN","symbol"=>"₼"),
			  array("country"=>"Azerbaijan","currency"=>"Azerbaijani Manat","code"=>"AZN","symbol"=>"₼"),
			  array("country"=>"Bahamas","currency"=>"Bahamian Dollar","code"=>"BSD","symbol"=>"$"),
			  array("country"=>"Bahrain","currency"=>"Bahraini Dinar","code"=>"BHD","symbol"=>".د.ب"),
			  array("country"=>"Bangladesh","currency"=>"Bangladeshi Taka","code"=>"BDT","symbol"=>"৳"),
			  array("country"=>"Barbados","currency"=>"Barbados Dollar","code"=>"BBD","symbol"=>"$"),
			  array("country"=>"Belarus","currency"=>"Belarusian Ruble","code"=>"BYR","symbol"=>"Br"),
			  array("country"=>"Belgium","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Belize","currency"=>"Belize Dollar","code"=>"BZD","symbol"=>"BZ$"),
			  array("country"=>"Benin","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Bhutan","currency"=>"Bhutanese Ngultrum","code"=>"BTN","symbol"=>"Nu."),
			  array("country"=>"Bolivia","currency"=>"Bolivian Boliviano","code"=>"BOB","symbol"=>'$b'),
			  array("country"=>"Bosnia and Herzegovina","currency"=>"Bosnia-Herzegovina Convertible Mark","code"=>"BAM","symbol"=>"KM"),
			  array("country"=>"Botswana","currency"=>"Botswana Pula","code"=>"BWP","symbol"=>"P"),
			  array("country"=>"Brazil","currency"=>"Brazilian Real","code"=>"BRL","symbol"=>"R$"),
			  array("country"=>"Brunei","currency"=>"Brunei Dollar","code"=>"BND","symbol"=>"$"),
			  array("country"=>"Bulgaria","currency"=>"Bulgarian Lev","code"=>"BGN","symbol"=>"лв"),
			  array("country"=>"Burkina Faso","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Burundi","currency"=>"Burundian Franc","code"=>"BIF","symbol"=>"FBu"),
			  array("country"=>"Cabo Verde","currency"=>"Cape Verde Escudo","code"=>"CVE","symbol"=>"$"),
			  array("country"=>"Cambodia","currency"=>"Cambodian Riel","code"=>"KHR","symbol"=>"៛"),
			  array("country"=>"Cameroon","currency"=>"Central African CFA","code"=>"XAF","symbol"=>"FCFA"),
			  array("country"=>"Canada","currency"=>"Canadian Dollar","code"=>"CAD","symbol"=>"$"),
			  array("country"=>"Central African Republic (CAR)","currency"=>"Central African CFA","code"=>"XAF","symbol"=>"FCFA"),
			  array("country"=>"Chad","currency"=>"Central African CFA","code"=>"XAF","symbol"=>"FCFA"),
			  array("country"=>"Chile","currency"=>"Chilean Peso","code"=>"CLP","symbol"=>"$"),
			  array("country"=>"China","currency"=>"Chinese Yuan Renminbi","code"=>"CNY","symbol"=>"¥"),
			  array("country"=>"Colombia","currency"=>"Colombian Peso","code"=>"COP","symbol"=>"$"),
			  array("country"=>"Comoros","currency"=>"Comorian Franc","code"=>"KMF","symbol"=>"CF"),
			  array("country"=>"Costa Rica","currency"=>"Costa Rican Colon","code"=>"CRC","symbol"=>"₡"),
			  array("country"=>"Cote d'Ivoire","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Croatia","currency"=>"Croatian Kuna","code"=>"HRK","symbol"=>"kn"),
			  array("country"=>"Cuba","currency"=>"Cuban Convertible Peso","code"=>"CUC","symbol"=>"$"),
			  array("country"=>"Cyprus","currency"=>"Cypriot Pound","code"=>"CYP","symbol"=>"£"),
			  array("country"=>"Cyprus","currency"=>"Cypriot Pound","code"=>"CYP","symbol"=>"£"),
			  array("country"=>"Czech Republic","currency"=>"Czech Koruna","code"=>"CZK","symbol"=>"Kč"),
			  array("country"=>"Democratic Republic of the Congo","currency"=>"Congolese franc","code"=>"CDF","symbol"=>"FC"),
			  array("country"=>"Denmark","currency"=>"Danish Krone","code"=>"DKK","symbol"=>"kr."),
			  array("country"=>"Djibouti","currency"=>"Djiboutian Franc","code"=>"DJF","symbol"=>"Fdj"),
			  array("country"=>"Dominica","currency"=>"East Caribbean Dollar","code"=>"XCD","symbol"=>"$"),
			  array("country"=>"Dominican Republic","currency"=>"Dominican Peso","code"=>"DOP","symbol"=>"RD$"),
			  array("country"=>"Ecuador","currency"=>"United States Dollar","code"=>"USD","symbol"=>"$"),
			  array("country"=>"Egypt","currency"=>"Egyptian Pound","code"=>"EGP","symbol"=>"£"),
			  array("country"=>"El Salvador","currency"=>"United States Dollar","code"=>"USD","symbol"=>"$"),
			  array("country"=>"Equatorial Guinea","currency"=>"Central African CFA","code"=>"XAF","symbol"=>"FCFA"),
			  array("country"=>"Eritrea","currency"=>"Eritrean Nakfa","code"=>"ERN","symbol"=>"ናቕፋ"),
			  array("country"=>"Estonia","currency"=>"Estonian Kroon","code"=>"EEK","symbol"=>"EEK"),
			  array("country"=>"Ethiopia","currency"=>"Ethiopian Birr","code"=>"ETB","symbol"=>"ብር"),
			  array("country"=>"Fiji","currency"=>"Fiji Dollar","code"=>"FJD","symbol"=>"$"),
			  array("country"=>"Finland","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"France","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Gabon","currency"=>"Central African CFA","code"=>"XAF","symbol"=>"FCFA"),
			  array("country"=>"Gambia","currency"=>"Gambian Dalasi","code"=>"GMD","symbol"=>"D"),
			  array("country"=>"Georgia","currency"=>"Georgian Lari","code"=>"GEL","symbol"=>"ლ"),
			  array("country"=>"Georgia","currency"=>"Georgian Lari","code"=>"GEL","symbol"=>"ლ"),
			  array("country"=>"Germany","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Ghana","currency"=>"Ghanaian Cedi","code"=>"GHC","symbol"=>"GH₵"),
			  array("country"=>"Greece","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Grenada","currency"=>"East Caribbean Dollar","code"=>"XCD","symbol"=>"$"),
			  array("country"=>"Guatemala","currency"=>"Guatemalan Quetzal","code"=>"GTQ","symbol"=>"Q"),
			  array("country"=>"Guinea","currency"=>"Guinean Franc","code"=>"GNF","symbol"=>"FG"),
			  array("country"=>"Guinea-Bissau","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Guyana","currency"=>"Guyanese Dollar","code"=>"GYD","symbol"=>"$"),
			  array("country"=>"Haiti","currency"=>"Haitian Gourde","code"=>"HTG","symbol"=>"G"),
			  array("country"=>"Honduras","currency"=>"Honduran Lempira","code"=>"HNL","symbol"=>"L"),
			  array("country"=>"Hungary","currency"=>"Hungarian Forint","code"=>"HUF","symbol"=>"Ft"),
			  array("country"=>"Iceland","currency"=>"Icelandic Krona","code"=>"ISK","symbol"=>"kr"),
			  array("country"=>"India","currency"=>"Indian Rupee","code"=>"INR","symbol"=>"₹"),
			  array("country"=>"Indonesia","currency"=>"Indonesian Rupiah","code"=>"IDR","symbol"=>"Rp"),
			  array("country"=>"Iran","currency"=>"Iranian Rial","code"=>"IRR","symbol"=>"﷼"),
			  array("country"=>"Iraq","currency"=>"Iraqi Dinar","code"=>"IQD","symbol"=>"ع.د"),
			  array("country"=>"Ireland","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Israel","currency"=>"Israeli New Sheqel","code"=>"ILS","symbol"=>"₪"),
			  array("country"=>"Italy","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Jamaica","currency"=>"Jamaican Dollar","code"=>"JMD","symbol"=>"J$"),
			  array("country"=>"Japan","currency"=>"Japanese Yen","code"=>"JPY","symbol"=>"¥"),
			  array("country"=>"Jordan","currency"=>"Jordanian Dinar","code"=>"JOD","symbol"=>"د.ا"),
			  array("country"=>"Kazakhstan","currency"=>"Kazakhstani Tenge","code"=>"KZT","symbol"=>"лв"),
			  array("country"=>"Kazakhstan","currency"=>"Kazakhstani Tenge","code"=>"KZT","symbol"=>"лв"),
			  array("country"=>"Kenya","currency"=>"Kenyan Shilling","code"=>"KES","symbol"=>"KSh,"),
			  array("country"=>"Kiribati","currency"=>"Australian Dollar","code"=>"AUD","symbol"=>"$"),
			  array("country"=>"Kosovo","currency"=>"Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Kuwait","currency"=>"Kuwaiti Dinar","code"=>"KWD","symbol"=>"د.ك"),
			  array("country"=>"Kyrgyzstan","currency"=>"Kyrgyzstani Som","code"=>"KGS","symbol"=>"лв"),
			  array("country"=>"Laos","currency"=>"Lao Kip","code"=>"LAK","symbol"=>"₭"),
			  array("country"=>"Latvia","currency"=>"Latvian Lats","code"=>"LVL","symbol"=>"Ls"),
			  array("country"=>"Lebanon","currency"=>"Lebanese Pound","code"=>"LBP","symbol"=>"£"),
			  array("country"=>"Lesotho","currency"=>"Lesotho Loti","code"=>"LSL","symbol"=>"L"),
			  array("country"=>"Liberia","currency"=>"Liberian Dollar","code"=>"LRD","symbol"=>"$"),
			  array("country"=>"Libya","currency"=>"Libyan Dinar","code"=>"LYD","symbol"=>"ل.د"),
			  array("country"=>"Liechtenstein","currency"=>"Swiss Franc","code"=>"CHF","symbol"=>"CHF"),
			  array("country"=>"Lithuania","currency"=>"Lithuanian Litas","code"=>"LTL","symbol"=>"Lt"),
			  array("country"=>"Luxembourg","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Macedonia (FYROM)","currency"=>"Macedonian Denar","code"=>"MKD","symbol"=>"ден"),
			  array("country"=>"Madagascar","currency"=>"Malagasy Ariary","code"=>"MGA","symbol"=>"Ar"),
			  array("country"=>"Malawi","currency"=>"Malawian Kwacha","code"=>"MWK","symbol"=>"MK"),
			  array("country"=>"Malaysia","currency"=>"Malaysian Ringgit","code"=>"MYR","symbol"=>"RM"),
			  array("country"=>"Maldives","currency"=>"Maldives Rufiyaa","code"=>"MVR","symbol"=>"Rf"),
			  array("country"=>"Mali","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Malta","currency"=>"Maltese Lira","code"=>"MTL","symbol"=>"₤"),
			  array("country"=>"Marshall Islands","currency"=>"United States Dollar","code"=>"USD","symbol"=>"$"),
			  array("country"=>"Mauritania","currency"=>"Mauritanian Ouguiya","code"=>"MRO","symbol"=>"UM"),
			  array("country"=>"Mauritius","currency"=>"Mauritian Rupee","code"=>"MUR","symbol"=>"₨"),
			  array("country"=>"Mexico","currency"=>"Mexican Peso","code"=>"MXN","symbol"=>"$"),
			  array("country"=>"Micronesia","currency"=>"United States Dollar","code"=>"USD","symbol"=>"$"),
			  array("country"=>"Moldova","currency"=>"Moldovan Leu","code"=>"MDL","symbol"=>"L"),
			  array("country"=>"Monaco","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Mongolia","currency"=>"Mongolian Tugrik","code"=>"MNT","symbol"=>"₮"),
			  array("country"=>"Montenegro","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Morocco","currency"=>"Moroccan Dirham","code"=>"MAD","symbol"=>"DH"),
			  array("country"=>"Mozambique","currency"=>"Mozambican Metical","code"=>"MZN","symbol"=>"MT"),
			  array("country"=>"Myanmar (Burma)","currency"=>"Myanmar Kyat","code"=>"MMK","symbol"=>"K"),
			  array("country"=>"Namibia","currency"=>"Namibian Dollar","code"=>"NAD","symbol"=>"$"),
			  array("country"=>"Nauru","currency"=>"Australian Dollar","code"=>"AUD","symbol"=>"$"),
			  array("country"=>"Nepal","currency"=>"Nepalese Rupee","code"=>"NPR","symbol"=>"₨"),
			  array("country"=>"Netherlands","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"New Zealand","currency"=>"New Zealand Dollar","code"=>"NZD","symbol"=>"$"),
			  array("country"=>"Nicaragua","currency"=>"Nicaraguan Córdoba","code"=>"NIO","symbol"=>"C$"),
			  array("country"=>"Niger","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Nigeria","currency"=>"Nigerian Naira","code"=>"NGN","symbol"=>"₦"),
			  array("country"=>"North Korea","currency"=>"North Korean Won","code"=>"KPW","symbol"=>"₩"),
			  array("country"=>"Norway","currency"=>"Norwegian Krone","code"=>"NOK","symbol"=>"kr"),
			  array("country"=>"Oman","currency"=>"Omani Rial","code"=>"OMR","symbol"=>"﷼"),
			  array("country"=>"Pakistan","currency"=>"Pakistan Rupee","code"=>"PKR","symbol"=>"₨"),
			  array("country"=>"Palau","currency"=>"United States Dollar","code"=>"USD","symbol"=>"$"),
			  array("country"=>"Palestine","currency"=>"Jordanian Dinar","code"=>"JOD","symbol"=>"د.ا"),
			  array("country"=>"Panama","currency"=>"Panamanian Balboa","code"=>"PAB","symbol"=>"B/."),
			  array("country"=>"Papua New Guinea","currency"=>"Papua New Guinea Kina","code"=>"PGK","symbol"=>"K"),
			  array("country"=>"Paraguay","currency"=>"Paraguay Guarani","code"=>"PYG","symbol"=>"Gs"),
			  array("country"=>"Peru","currency"=>"Peruvian Nuevo Sol","code"=>"PEN","symbol"=>"S/."),
			  array("country"=>"Philippines","currency"=>"Philippine Peso","code"=>"PHP","symbol"=>"₱"),
			  array("country"=>"Poland","currency"=>"Polish Zloty","code"=>"PLN","symbol"=>"zł"),
			  array("country"=>"Portugal","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Qatar","currency"=>"Qatari Riyal","code"=>"QAR","symbol"=>"﷼"),
			  array("country"=>"Republic of the Congo","currency"=>"Central African CFA","code"=>"XAF","symbol"=>"FCFA"),
			  array("country"=>"Romania","currency"=>"Romanian Leu","code"=>"RON","symbol"=>"lei"),
			  array("country"=>"Russia","currency"=>"Russian Ruble","code"=>"RUB","symbol"=>"₽"),
			  array("country"=>"Russia","currency"=>"Russian Ruble","code"=>"RUB","symbol"=>"₽"),
			  array("country"=>"Rwanda","currency"=>"Rwandan Franc","code"=>"RWF","symbol"=>"FRw"),
			  array("country"=>"Saint Kitts and Nevis","currency"=>"East Caribbean Dollar","code"=>"XCD","symbol"=>"$"),
			  array("country"=>"Saint Lucia","currency"=>"East Caribbean Dollar","code"=>"XCD","symbol"=>"$"),
			  array("country"=>"Saint Vincent and the Grenadines","currency"=>"East Caribbean Dollar","code"=>"XCD","symbol"=>"$"),
			  array("country"=>"Samoa","currency"=>"Samoan Tala","code"=>"WST","symbol"=>"WS$"),
			  array("country"=>"San Marino","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Sao Tome and Principe","currency"=>"Sao Tome Dobra","code"=>"STD","symbol"=>"Db"),
			  array("country"=>"Saudi Arabia","currency"=>"Saudi Arabian Riyal","code"=>"SAR","symbol"=>"﷼"),
			  array("country"=>"Senegal","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Serbia","currency"=>"Serbian Dinar","code"=>"RSD","symbol"=>"Дин."),
			  array("country"=>"Seychelles","currency"=>"Seychelles Rupee","code"=>"SCR","symbol"=>"₨"),
			  array("country"=>"Sierra Leone","currency"=>"Sierra Leonean Leone","code"=>"SLL","symbol"=>"Le"),
			  array("country"=>"Singapore","currency"=>"Singapore Dollar","code"=>"SGD","symbol"=>"$"),
			  array("country"=>"Slovakia","currency"=>"Slovak Koruna","code"=>"SKK","symbol"=>"Sk"),
			  array("country"=>"Slovenia","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Solomon Islands","currency"=>"Solomon Islands Dollar","code"=>"SBD","symbol"=>"$"),
			  array("country"=>"Somalia","currency"=>"Somali Shilling","code"=>"SOS","symbol"=>"S"),
			  array("country"=>"South Africa","currency"=>"South African Rand","code"=>"ZAR","symbol"=>"R"),
			  array("country"=>"South Korea","currency"=>"Korean Won","code"=>"KRW","symbol"=>"₩"),
			  array("country"=>"South Sudan","currency"=>"South Sudanese pound","code"=>"SSP","symbol"=>"£"),
			  array("country"=>"Spain","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Sri Lanka","currency"=>"Sri Lankan Rupee","code"=>"LKR","symbol"=>"₨"),
			  array("country"=>"Sudan","currency"=>"Sudanese pound","code"=>"SDG","symbol"=>"SD"),
			  array("country"=>"Suriname","currency"=>"Suriname Dollar","code"=>"SRD","symbol"=>"$"),
			  array("country"=>"Swaziland","currency"=>"Swazi Lilangeni","code"=>"SZL","symbol"=>"E"),
			  array("country"=>"Sweden","currency"=>"Swedish Krona","code"=>"SEK","symbol"=>"kr"),
			  array("country"=>"Switzerland","currency"=>"Swiss Franc","code"=>"CHF","symbol"=>"CHF"),
			  array("country"=>"Syria","currency"=>"Syrian Pound","code"=>"SYP","symbol"=>"£"),
			  array("country"=>"Taiwan","currency"=>"New Taiwan Dollar","code"=>"TWD","symbol"=>"NT$"),
			  array("country"=>"Tajikistan","currency"=>"Tajikistan Somoni","code"=>"TJS","symbol"=>"ЅM"),
			  array("country"=>"Tanzania","currency"=>"Tanzanian Shilling","code"=>"TZS","symbol"=>"TSh"),
			  array("country"=>"Thailand","currency"=>"Thai Baht","code"=>"THB","symbol"=>"฿"),
			  array("country"=>"Timor-Leste","currency"=>"United States Dollar","code"=>"USD","symbol"=>"$"),
			  array("country"=>"Togo","currency"=>"West African CFA","code"=>"XOF","symbol"=>"CFA"),
			  array("country"=>"Tonga","currency"=>"Tongan Pa'Anga","code"=>"TOP","symbol"=>"T$"),
			  array("country"=>"Trinidad and Tobago","currency"=>"Trinidad and Tobago Dollar","code"=>"TTD","symbol"=>"TT$"),
			  array("country"=>"Tunisia","currency"=>"Tunisian Dinar","code"=>"TND","symbol"=>"د.ت"),
			  array("country"=>"Turkey","currency"=>"Turkish New Lira","code"=>"TRY","symbol"=>"₺"),
			  array("country"=>"Turkey","currency"=>"Turkish New Lira","code"=>"TRY","symbol"=>"₺"),
			  array("country"=>"Turkmenistan","currency"=>"Turkmenistani Manat","code"=>"TMM","symbol"=>"T"),
			  array("country"=>"Tuvalu","currency"=>"Australian Dollar","code"=>"AUD","symbol"=>"$"),
			  array("country"=>"Uganda","currency"=>"Ugandan Shilling","code"=>"UGX","symbol"=>"USh"),
			  array("country"=>"Ukraine","currency"=>"Ukrainian Hryvnia","code"=>"UAH","symbol"=>"₴"),
			  array("country"=>"United Arab Emirates (UAE)","currency"=>"United Arab Emirates Dirham","code"=>"AED","symbol"=>"د.إ"),
			  array("country"=>"United Kingdom (UK)","currency"=>"United Kingdom Pound Sterling","code"=>"GBP","symbol"=>"£"),
			  array("country"=>"United States of America (USA)","currency"=>"United States Dollar","code"=>"USD","symbol"=>"$"),
			  array("country"=>"Uruguay","currency"=>"Uruguayan peso","code"=>"UYU","symbol"=>'$U'),
			  array("country"=>"Uzbekistan","currency"=>"Uzbekistani Som","code"=>"UZS","symbol"=>"лв"),
			  array("country"=>"Vanuatu","currency"=>"Vanuatu Vatu","code"=>"VUV","symbol"=>"VT"),
			  array("country"=>"Vatican City (Holy See)","currency"=>"European Euro","code"=>"EUR","symbol"=>"€"),
			  array("country"=>"Venezuela","currency"=>"Venezuelan Bolivar","code"=>"VEF","symbol"=>"Bs"),
			  array("country"=>"Vietnam","currency"=>"Viet Nam Dong","code"=>"VND","symbol"=>"₫"),
			  array("country"=>"Yemen","currency"=>"Yemeni Rial","code"=>"YER","symbol"=>"﷼"),
			  array("country"=>"Zambia","currency"=>"Zambian Kwacha","code"=>"ZMK","symbol"=>"ZK"),
			  array("country"=>"Zimbabwe","currency"=>"Zimbabwean Dollar","code"=>"ZWD","symbol"=>"$")
			);


		for ($i=0; $i < count($country); $i++) { 

		    CountryCurrencySymbol::create(['country'=>$country[$i]['country'], 'currency'=>$country[$i]['currency'], 'code'=>$country[$i]['code'], 'symbol'=>$country[$i]['symbol']]);
		}
    }
}
